development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Mobiledic
  admin_email: ochkoo@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Mobiledic
  admin_email: ochkoo@gmail.com  
  
production:
  site_url: http://mobiledic.sequelist.com
  site_name: Mobiledic
  admin_email: ochkoo@gmail.com
